"""Create the initial PostgreSQL schema.

Revision ID: 0001_postgres_schema
Revises: None
"""
from alembic import op


revision = "0001_postgres_schema"
down_revision = None
branch_labels = None
depends_on = None


STATEMENTS = [
    "CREATE EXTENSION IF NOT EXISTS citext",
    """CREATE TABLE users (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username citext NOT NULL UNIQUE, password_salt bytea NOT NULL, password_hash bytea NOT NULL, created_at timestamptz NOT NULL)""",
    """CREATE TABLE sessions (token_hash varchar(64) PRIMARY KEY, username citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL)""",
    "CREATE INDEX ix_sessions_username ON sessions(username)",
    "CREATE INDEX ix_sessions_expires_at ON sessions(expires_at)",
    """CREATE TABLE roles (name text PRIMARY KEY, description text NOT NULL)""",
    """CREATE TABLE user_roles (username citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE, role_name text NOT NULL REFERENCES roles(name), PRIMARY KEY(username, role_name))""",
    """CREATE TABLE user_profiles (username citext PRIMARY KEY REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE, display_name text NOT NULL, active integer NOT NULL DEFAULT 1 CHECK(active IN (0,1)), must_change_password integer NOT NULL DEFAULT 0 CHECK(must_change_password IN (0,1)), updated_at timestamptz NOT NULL)""",
    """CREATE TABLE accounts (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name citext NOT NULL UNIQUE, active integer NOT NULL DEFAULT 1 CHECK(active IN (0,1)), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL)""",
    """CREATE TABLE account_config (account_id bigint PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE, coverage_enabled integer NOT NULL DEFAULT 0 CHECK(coverage_enabled IN (0,1)), coverage_period text NOT NULL DEFAULT 'week' CHECK(coverage_period IN ('day','week','month')), audits_per_associate integer NOT NULL DEFAULT 3 CHECK(audits_per_associate > 0), identifier_column_default text, associate_column_default text, exclude_previously_sampled integer NOT NULL DEFAULT 1 CHECK(exclude_previously_sampled IN (0,1)), case_insensitive_ids integer NOT NULL DEFAULT 1 CHECK(case_insensitive_ids IN (0,1)), updated_at timestamptz NOT NULL)""",
    """CREATE TABLE processes (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id bigint NOT NULL REFERENCES accounts(id), name citext NOT NULL, process_type text NOT NULL CHECK(process_type IN ('front_office','back_office')), timezone text NOT NULL DEFAULT 'local', target_yield double precision NOT NULL DEFAULT 95 CHECK(target_yield BETWEEN 0 AND 100), target_sigma double precision NOT NULL DEFAULT 3 CHECK(target_sigma BETWEEN 0 AND 6), active integer NOT NULL DEFAULT 1 CHECK(active IN (0,1)), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, UNIQUE(account_id,name), UNIQUE(id,account_id))""",
    """CREATE TABLE process_settings (process_id bigint PRIMARY KEY REFERENCES processes(id) ON DELETE CASCADE, sampling_frequency text NOT NULL DEFAULT 'weekly', sampling_count integer NOT NULL DEFAULT 10 CHECK(sampling_count > 0), assignment_mode text NOT NULL DEFAULT 'unassigned', subgroup_mode text NOT NULL DEFAULT 'day' CHECK(subgroup_mode IN ('day','week','month')), baseline_subgroups integer NOT NULL DEFAULT 20 CHECK(baseline_subgroups >= 5), critical_capa_enabled integer NOT NULL DEFAULT 1 CHECK(critical_capa_enabled IN (0,1)), capa_due_days integer NOT NULL DEFAULT 14 CHECK(capa_due_days BETWEEN 1 AND 365), import_mapping_json text NOT NULL DEFAULT '{}', updated_at timestamptz NOT NULL)""",
    """CREATE TABLE uploads (upload_id text PRIMARY KEY, original_name text NOT NULL, stored_path text NOT NULL, file_type text NOT NULL, sha256 text NOT NULL, size_bytes bigint NOT NULL CHECK(size_bytes >= 0), created_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'READY' CHECK(status IN ('READY','USED','EXPIRED','ERROR')))""",
    "CREATE INDEX ix_uploads_status_created ON uploads(status,created_at)",
    """CREATE TABLE sampling_runs (run_id text PRIMARY KEY, account_id bigint NOT NULL REFERENCES accounts(id), process_id bigint NOT NULL, upload_id text REFERENCES uploads(upload_id) ON DELETE SET NULL, source_filename text NOT NULL, source_hash text NOT NULL, sheet_name text NOT NULL, header_row integer NOT NULL, identifier_column text NOT NULL, associate_column text, sampling_method text NOT NULL, requested_count integer NOT NULL CHECK(requested_count > 0), eligible_count integer NOT NULL, selected_count integer NOT NULL, seed text NOT NULL, algorithm_version text NOT NULL, coverage_enabled integer NOT NULL DEFAULT 0 CHECK(coverage_enabled IN (0,1)), coverage_period text, coverage_quota integer, period_key text, filters_json text NOT NULL DEFAULT '[]', validation_json text NOT NULL DEFAULT '{}', coverage_summary_json text NOT NULL DEFAULT '{}', app_version text NOT NULL DEFAULT '', created_at timestamptz NOT NULL, created_by citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE, status text NOT NULL DEFAULT 'COMPLETED' CHECK(status IN ('COMPLETED','VOIDED')), void_reason text, voided_at timestamptz, voided_by citext REFERENCES users(username) ON UPDATE CASCADE, FOREIGN KEY(process_id,account_id) REFERENCES processes(id,account_id))""",
    "CREATE INDEX ix_runs_account ON sampling_runs(account_id,created_at DESC)",
    "CREATE INDEX ix_runs_process ON sampling_runs(process_id,created_at DESC)",
    """CREATE TABLE sample_records (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id text NOT NULL REFERENCES sampling_runs(run_id) ON DELETE CASCADE, identifier_raw text NOT NULL, normalized_identifier text NOT NULL, associate text, selection_sequence integer NOT NULL CHECK(selection_sequence > 0), row_json text NOT NULL, period_key text, selected_at timestamptz NOT NULL, UNIQUE(run_id,selection_sequence))""",
    "CREATE INDEX ix_sample_identifier ON sample_records(normalized_identifier)",
    "CREATE INDEX ix_sample_run ON sample_records(run_id)",
    """CREATE TABLE scorecard_versions (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, process_id bigint NOT NULL REFERENCES processes(id), name text NOT NULL, version integer NOT NULL CHECK(version > 0), status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','PUBLISHED','ARCHIVED')), passing_score double precision NOT NULL DEFAULT 85 CHECK(passing_score BETWEEN 0 AND 100), opportunities_per_unit integer NOT NULL DEFAULT 1 CHECK(opportunities_per_unit > 0), critical_fail_override integer NOT NULL DEFAULT 1 CHECK(critical_fail_override IN (0,1)), created_at timestamptz NOT NULL, created_by citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE, published_at timestamptz, UNIQUE(process_id,version))""",
    "CREATE UNIQUE INDEX ux_scorecard_published ON scorecard_versions(process_id) WHERE status='PUBLISHED'",
    """CREATE TABLE scorecard_items (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, scorecard_version_id bigint NOT NULL REFERENCES scorecard_versions(id) ON DELETE CASCADE, item_type text NOT NULL CHECK(item_type IN ('question','defect','sla')), category text NOT NULL DEFAULT 'General', name text NOT NULL, weight double precision NOT NULL DEFAULT 0 CHECK(weight BETWEEN 0 AND 100), severity text NOT NULL DEFAULT 'Minor', critical integer NOT NULL DEFAULT 0 CHECK(critical IN (0,1)), opportunity_count integer NOT NULL DEFAULT 1 CHECK(opportunity_count > 0), target double precision, lsl double precision, usl double precision, unit text, sort_order integer NOT NULL DEFAULT 0, active integer NOT NULL DEFAULT 1 CHECK(active IN (0,1)))""",
    """CREATE TABLE audit_cases (audit_id text PRIMARY KEY, process_id bigint NOT NULL REFERENCES processes(id), sample_record_id bigint REFERENCES sample_records(id) ON DELETE SET NULL, external_case_id text, scorecard_version_id bigint REFERENCES scorecard_versions(id), assigned_to text, status text NOT NULL DEFAULT 'UNASSIGNED', associate text, source_json text NOT NULL DEFAULT '{}', started_at timestamptz, submitted_at timestamptz, reviewed_at timestamptz, reviewed_by citext REFERENCES users(username) ON UPDATE CASCADE, rejection_reason text, weighted_score double precision, passed integer CHECK(passed IN (0,1)), critical_fail integer NOT NULL DEFAULT 0 CHECK(critical_fail IN (0,1)), opportunities integer NOT NULL DEFAULT 1 CHECK(opportunities > 0), defect_count integer NOT NULL DEFAULT 0 CHECK(defect_count >= 0), created_at timestamptz NOT NULL, created_by citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE, void_reason text)""",
    "CREATE UNIQUE INDEX ux_audit_external_case ON audit_cases(process_id,external_case_id) WHERE external_case_id IS NOT NULL",
    "CREATE UNIQUE INDEX ux_audit_sample_record ON audit_cases(sample_record_id) WHERE sample_record_id IS NOT NULL",
    "CREATE INDEX ix_audits_process_status ON audit_cases(process_id,status,submitted_at)",
    """CREATE TABLE audit_responses (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, audit_id text NOT NULL REFERENCES audit_cases(audit_id) ON DELETE CASCADE, item_id bigint NOT NULL REFERENCES scorecard_items(id), passed integer CHECK(passed IN (0,1)), score double precision, numeric_value double precision, notes text, UNIQUE(audit_id,item_id))""",
    """CREATE TABLE audit_defects (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, audit_id text NOT NULL REFERENCES audit_cases(audit_id) ON DELETE CASCADE, item_id bigint REFERENCES scorecard_items(id) ON DELETE SET NULL, category text NOT NULL, name text NOT NULL, severity text NOT NULL, critical integer NOT NULL DEFAULT 0 CHECK(critical IN (0,1)), opportunities integer NOT NULL DEFAULT 1 CHECK(opportunities > 0), created_at timestamptz NOT NULL)""",
    "CREATE INDEX ix_defects_audit ON audit_defects(audit_id)",
    """CREATE TABLE result_imports (import_id text PRIMARY KEY, filename text NOT NULL, sha256 text NOT NULL, status text NOT NULL DEFAULT 'PREVIEW', columns_json text NOT NULL, mapping_json text NOT NULL DEFAULT '{}', row_count integer NOT NULL, error_count integer NOT NULL DEFAULT 0 CHECK(error_count >= 0), created_by citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE, created_at timestamptz NOT NULL, committed_at timestamptz)""",
    """CREATE TABLE result_import_rows (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, import_id text NOT NULL REFERENCES result_imports(import_id) ON DELETE CASCADE, row_number integer NOT NULL CHECK(row_number > 0), row_json text NOT NULL, status text NOT NULL DEFAULT 'READY', error text, audit_id text REFERENCES audit_cases(audit_id) ON DELETE SET NULL, UNIQUE(import_id,row_number))""",
    "CREATE INDEX ix_import_rows_status ON result_import_rows(import_id,status)",
    """CREATE TABLE capas (capa_id text PRIMARY KEY, process_id bigint NOT NULL REFERENCES processes(id), audit_id text REFERENCES audit_cases(audit_id) ON DELETE SET NULL, title text NOT NULL, priority text NOT NULL DEFAULT 'MEDIUM', stage text NOT NULL DEFAULT 'DRAFT', owner text, due_date date, containment text NOT NULL DEFAULT '', root_cause text NOT NULL DEFAULT '', action_plan text NOT NULL DEFAULT '', implementation_notes text NOT NULL DEFAULT '', effectiveness text NOT NULL DEFAULT '', created_at timestamptz NOT NULL, created_by citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE, updated_at timestamptz NOT NULL, closed_at timestamptz)""",
    "CREATE UNIQUE INDEX ux_capa_audit ON capas(audit_id) WHERE audit_id IS NOT NULL",
    "CREATE INDEX ix_capa_process_stage ON capas(process_id,stage,due_date)",
    """CREATE TABLE capa_events (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, capa_id text NOT NULL REFERENCES capas(capa_id) ON DELETE CASCADE, event_type text NOT NULL, from_stage text, to_stage text, detail_json text NOT NULL DEFAULT '{}', username citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE, created_at timestamptz NOT NULL)""",
    "CREATE INDEX ix_capa_events_created ON capa_events(capa_id,created_at)",
    """CREATE TABLE app_settings (key text PRIMARY KEY, value_json text NOT NULL, updated_at timestamptz NOT NULL, updated_by citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE)""",
    """CREATE TABLE audit_events (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_type text NOT NULL, username citext NOT NULL REFERENCES users(username) ON UPDATE CASCADE, entity_type text, entity_id text, detail_json text NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL)""",
    "CREATE INDEX ix_audit_events_created ON audit_events(created_at DESC)",
    "CREATE INDEX ix_audit_events_entity ON audit_events(entity_type,entity_id)",
]


def upgrade() -> None:
    for statement in STATEMENTS:
        op.execute(statement)
    op.execute("""INSERT INTO roles(name,description) VALUES
        ('Administrator','Full configuration and system access'),
        ('QA Auditor','Create samples and complete assigned audits'),
        ('QA Reviewer','Review audits and manage CAPA evidence'),
        ('Operations Manager','View analytics, reports, and approve CAPA')
        ON CONFLICT(name) DO NOTHING""")


def downgrade() -> None:
    for table in [
        "audit_events", "app_settings", "capa_events", "capas", "result_import_rows", "result_imports",
        "audit_defects", "audit_responses", "audit_cases", "scorecard_items", "scorecard_versions",
        "sample_records", "sampling_runs", "uploads", "process_settings", "processes", "account_config",
        "accounts", "user_profiles", "user_roles", "roles", "sessions", "users",
    ]:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
